language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install npm nodejs
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - sudo apt-get -qq update
  - sudo apt-get install sbt
script:
  - sh ./git-lfs.sh
  - sh ./openmole.sh
  - sh ./gama.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
branches:
  only:
    - 7-dev