#!/bin/bash

(cd openmole && \
    (cd build-system && sbt publishLocal) && \
    (cd libraries && sbt publishLocal) && \
    (cd openmole && sbt "project openmole" publishLocal))

sbt generateTask


